version: 1
names:
  family: Apple Color Emoji
bitmap:
  format: cbdt_cblc
  strikes:
    - 20
    - 26
    - 32
    - 40
    - 48
    - 52
    - 64
    - 96
  backfill_missing:
    source: 160
  metrics:
    y_bearing: full_height
tables:
  drop:
    source_tables: true
    outlines: true
  cmap:
    bmp: true
    ucs4: true
  metrics:
    fs_type: installable
    unicode_ranges: emoji
  head:
    mac_style: 0
    units_per_em: 2048
  post:
    format: 3
